services:

  perm-volume-fix-init:
    image: busybox
    container_name: fix_init
    user: "0:0"
    volumes:
      - temp_upload:/temp_upload
    command: sh -c "chown -R :1000 /temp_upload && chmod -R 775 /temp_upload"
    restart: "no"

  api:
    image: ghcr.io/kaleab-yaye/central_server_spring_image:latest
    container_name: stream_dist
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - temp_upload:/app/temp_upload
    environment:
      - TEMP_UPLOAD=./temp_upload
      - S3_URI=http://minio:9000
      - S3_ACCESS_KEY=ktadmin
      - S3_SECRET_ACCESS_KEY=12345678
    user: "1000:1000"

  encoder:
    build:
      context: .
      dockerfile: Dockerfile.encode
    container_name: encoder-dist
    image: encoder
    depends_on:
      - api
      - nginx
      - postgres
    environment:
      - RAW_VID=/data
      - PROC_ED=/encoded
      - S3_URI=http://minio:9000
      - S3_ACCESS_KEY=ktadmin
      - S3_SECRET_ACCESS_KEY=12345678
      - CENTERAL_CERV=http://api



  postgres:
    image: postgres:15-alpine
    container_name: db_dist
    environment:
      - POSTGRES_USER=devuser # psql -d streaming_api_db -U devuser
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_DB=streaming_api_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../db/log:/var/log/postgresql
    entrypoint:
      - bash
      - -c
      - |
        chown -R postgres:postgres /var/log/postgresql
        exec docker-entrypoint.sh "$$@"
      - "--"

    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgres-%Y-%m-%d.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=10MB"


  nginx:
    image: nginx:alpine
    container_name: streaming_proxy_dist
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - test_html:/store/html


  tusd:
    image: tusproject/tusd:sha-262f655
    container_name: tus-serv-dist_dist
    ports:
      - "1080:1080"
    volumes:
      - temp_upload:/srv/tusd-data
    user: "1001:1000"
    command: >
      -host=0.0.0.0 
      -port=1080 
      -upload-dir=/srv/tusd-data
      -hooks-http=http://api:8080/api/hooks/tusd/upload
      -hooks-http-retry=3
    depends_on:
      - api

volumes:
  db_data:
  test_html:
  temp_upload:
