
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;


    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain application/json text/css application/javascript;

    server {
        listen 80;
        server_name _;


        location /api/ {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /auth{
            internal;
        proxy_pass http://api:8080/api/v1/player/auth/vid;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header request_uri $request_uri;
        proxy_set_header current-frame $http_current_frame; # for incoming headers
        }


        location /vid/get/ {
            auth_request /auth;
            alias /store/videos/encoded/;
        }

        location /static/{
            alias /store/html/;
            expires 7d;
        }


        location /files{

        if ($request_method ~ ^(GET)$ ) {
            return 405;
        }
        client_max_body_size 0;
        proxy_pass http://tusd:1080;
        }
    }
}