ALTER TABLE vid ADD COLUMN upload_location VARCHAR(555) DEFAULT 'NOT_SPECIFIED';
ALTER TABLE vid ADD COLUMN encoded_location VARCHAR (555) DEFAULT  'NOT_SPECIFIED';
ALTER TABLE vid ADD COLUMN  size BIGINT;

