ALTER TYPE vid_state ADD VALUE 'ENCODER_DOWNLOAD_FROM_S3_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_UPLOAD_TO_S3_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_ZIP_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_NOT_VID_DELETE_OBJECT_S3_FAILER_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_BROKEN_VID_DELETE_OBJECT_S3_FAILER_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_ENCODERR_DELETE_OBJECT_S3_FAILER_FAILED';
ALTER TYPE vid_state ADD VALUE 'ENCODER_DELETE_OBJECT_S3_JOB_DONE_FAILED';