ALTER TYPE vid_state ADD VALUE 'ENCODING';
ALTER TYPE vid_state ADD VALUE 'REMOVED';
ALTER TYPE vid_state ADD VALUE 'NOT_VID';
ALTER TYPE vid_state ADD VALUE 'BROKEN_VID';
ALTER TABLE vid ADD COLUMN present BOOLEAN DEFAULT FALSE;
ALTER TABLE vid DROP CONSTRAINT vid_name_key;
CREATE INDEX vid_stat_index ON vid (vid_stat);