spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_api_db
    username: devuser
    password: devsecret


  jpa:
    hibernate:
      ddl-auto: none

  cache:
    type: caffeine
    cache-names:
      - privilege
    caffeine:
      spec: expireAfterWrite=60m

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 77cd646bc2c27c
    password: ccecb395e9de16
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




jwt:
  secret-key: "wM7QEMi5ljlugyydNZrHi2fp4Y6mZ9Ivm4efYDqNtUk="

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

      # will add this when we start having microservice sys
      #metrics:
      # tags:
      # application: some-service-name